"""Exercise the patched Android worker with the real pinned Moonraker parser."""
import ast
import asyncio
import base64
import importlib.util
import io
import os
from pathlib import Path
import sys
import tempfile
import types
import unittest
from typing import Any, Dict, Optional
from PIL import Image

ROOT = Path(__file__).resolve().parents[2]
VENDOR = ROOT / 'app/src/main/python/moonraker/components/file_manager'
package = types.ModuleType('android_metadata_test')
package.__path__ = [str(VENDOR)]
sys.modules[package.__name__] = package
spec = importlib.util.spec_from_file_location(package.__name__ + '.metadata', VENDOR / 'metadata.py')
metadata = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = metadata
spec.loader.exec_module(metadata)

# Load the actual patched methods without needing a running Moonraker server.
tree = ast.parse((VENDOR / 'file_manager.py').read_text())
methods = [node for node in ast.walk(tree) if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
           and node.name in ('_android_extract_metadata', '_run_extract_metadata')]
worker_tree = ast.Module(body=[ast.ClassDef(name='Worker', bases=[], keywords=[], body=methods,
                                          decorator_list=[])], type_ignores=[])
namespace = dict(__package__=package.__name__, os=os, Dict=Dict, Any=Any, Optional=Optional)
exec(compile(ast.fix_missing_locations(worker_tree), '<patched-worker>', 'exec'), namespace)
Worker = namespace['Worker']

class MetadataTests(unittest.TestCase):
    def setUp(self):
        self.temp = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp.cleanup)
        self.root = Path(self.temp.name)
        image = io.BytesIO()
        Image.new('RGB', (64, 64), 'blue').save(image, format='PNG')
        thumb = base64.b64encode(image.getvalue()).decode()
        self.gcode = (f'; generated by PrusaSlicer 2.9.0 on 2026-10-08 at 06:00:00\n; thumbnail begin 64x64 {len(thumb)}\n'
                      f'; {thumb}\n; thumbnail end\nG28\nG1 X1 Y1 Z0.2\n'
                      '; estimated printing time (normal mode) = 1h 2m 3s\n'
                      '; total layers count = 42\n')
        (self.root / 'sample.gcode').write_text(self.gcode)
        self.config = dict(filename='sample.gcode', gcode_dir=str(self.root), check_objects=False)

    def test_layer_count_eta_and_thumbnail(self):
        result = Worker._android_extract_metadata(self.config)['metadata']
        self.assertEqual(result['layer_count'], 42)
        self.assertEqual(result['estimated_time'], 3723)
        self.assertTrue(result['thumbnails'])
        for thumbnail in result['thumbnails']:
            path = self.root / thumbnail['relative_path']
            self.assertTrue(path.is_file())
            with Image.open(path) as image:
                image.verify()

    def test_nested_path_and_source_unchanged(self):
        (self.root / 'folder').mkdir()
        (self.root / 'folder/part.gcode').write_text(self.gcode)
        result = Worker._android_extract_metadata({**self.config, 'filename': 'folder/part.gcode'})
        self.assertEqual(result['file'], 'folder/part.gcode')
        self.assertEqual((self.root / 'folder/part.gcode').read_text(), self.gcode)

    def test_missing_file_is_recoverable_exception(self):
        with self.assertRaises(FileNotFoundError):
            Worker._android_extract_metadata({**self.config, 'filename': 'missing.gcode'})
        self.assertEqual(Worker._android_extract_metadata(self.config)['metadata']['layer_count'], 42)

    def test_parser_system_exit_does_not_exit_host(self):
        with self.assertRaises(RuntimeError):
            Worker._android_extract_metadata({**self.config, 'ufp_path': str(self.root / 'missing.ufp')})

    def test_minimal_gcode_does_not_invent_layers_or_eta(self):
        (self.root / 'plain.gcode').write_text('G28\nG1 X1 Y1\n')
        result = Worker._android_extract_metadata({**self.config, 'filename': 'plain.gcode'})['metadata']
        self.assertIsNone(result.get('layer_count'))
        self.assertIsNone(result.get('estimated_time'))

    def test_async_worker_saves_metadata_and_resets_job_fields(self):
        class Loop:
            async def run_in_thread(self, fn, config):
                return await asyncio.to_thread(fn, config)
        worker = Worker()
        worker.gc_path = str(self.root)
        worker.enable_object_proc = False
        worker.processors = {}
        worker.metadata = {}
        worker.mddb = {}
        worker.server = types.SimpleNamespace(get_event_loop=lambda: Loop(), error=RuntimeError)
        asyncio.run(worker._run_extract_metadata('sample.gcode', None))
        self.assertEqual(worker.metadata['sample.gcode']['layer_count'], 42)
        self.assertEqual(worker.metadata, worker.mddb)
        self.assertIsNone(worker.mddb['sample.gcode']['job_id'])

if __name__ == '__main__':
    unittest.main()
